[directories]
maps = "/maps"
data = "/gameData"
sprites = "/graphics"
output = "/generated"
# miscScripts = undefined

[scriptNamesToLevels]
PLAYERSHOUSE = "LITTLEROOT_TOWN"
CONTESTHALL = "LILYCOVE_CITY"

# Names of battles that are against the rival
[battles]
rivalBattles = [
    "TRAINER_RIVAL_SAKU_SNIVY",
    "TRAINER_RIVAL_SAKU_FROAKIE",
    "TRAINER_RIVAL_SAKU_CYNDAQUIL",
    "TRAINER_RIVAL_FIRST_BATTLE_FROAKIE",
    "TRAINER_RIVAL_FIRST_BATTLE_SNIVY",
    "TRAINER_RIVAL_FIRST_BATTLE_CYNDAQUIL"
]
#Scripts that have trainerbattles that can be skipped
skip = []
[maps]
hasNumberedRoutes = false