export const notneededLabels = [
  "FortreeCity_Gym_EventScript_GiveAerialAce2::",
  "CheatCodeMegaStones::",
  "LavaridgeTown_EventScript_BrendanGiveGoGoggles::",
  "LavaridgeTown_Gym_1F_EventScript_GiveOverheat2::",
  "MauvilleCity_Gym_EventScript_GiveVoltSwitch2::",
  "Route110_TrickHouseEnd_EventScript_CompletedPuzzle3::",
  "Route110_TrickHouseEnd_EventScript_CompletedPuzzle2::",
  "MauvilleCity_Gym_EventScript_GiveVoltSwitch2::",
  "SootopolisCity_Gym_1F_EventScript_GiveWaterPulse2::",
  "LittlerootTown_ProfessorBirchsLab_EventScript_BrendanGivePokeBalls::",
  "LittlerootTown_ProfessorBirchsLab_EventScript_BrendanGivePokeBalls",
  "Route110_TrickHouseEnd_EventScript_CompletedPuzzle6::",
  "MauvilleCity_BikeShop_EventScript_GetMachBike::",
  "MauvilleCity_BikeShop_EventScript_SwitchAcroForMach::",
  "MauvilleCity_BikeShop_EventScript_GetAcroBike::",
  "MauvilleCity_BikeShop_EventScript_SwitchMachForAcro::",
  "MossdeepCity_Gym_EventScript_GiveCalmMind2::",
  "MossdeepCity_SpaceCenter_1F_EventScript_SunStoneManMagma::",
  "Route110_TrickHouseEnd_EventScript_CompletedPuzzle1::",
  "Route110_TrickHouseEnd_EventScript_CompletedPuzzle4::",
  "Route110_TrickHouseEnd_EventScript_CompletedPuzzle5::",
  "Route110_TrickHouseEnd_EventScript_CompletedPuzzle7::",
  "OldaleTown_House2_EventScript_Man::",
  "CableClub_EventScript_DistributeEonTicket::",
  "MysteryGiftScript_MysticTicket::",
  "MysteryGiftScript_OldSeaMap::",
  "MysteryGiftScript_BattleCard::",
  "MysteryGiftScript_AuroraTicket::",
  "DewfordTown_Gym_EventScript_GiveLowSweep2::",
  "MauvilleCity_PokemonCenter_1F_EventScript_CostumePikachuGive_1::",
  "VictoryRoad_1F_EventScript_ConfirmAndUseSummon_1:",
  "VictoryRoad_1F_EventScript_ConfirmAndUseSummon::",
  "Route123_BerryMastersHouse_EventScript_GiveNormalBerry::",
  "ShoalCave_LowTideLowerRoom_EventScript_ConfirmAndUseSummon_1:",
  "Debug_CheatStart::",
  "SurfPichu_GiveEgg::",
  "SurfPichu_GiveEgg:",
  "Route109_SeashoreHouse_EventScript_DefeatedTrainers_3:",
  "Route123_BerryMastersHouse_EventScript_GivePamtreBerry::",
  "Route123_BerryMastersHouse_EventScript_GiveWatmelBerry::",
  "Route123_BerryMastersHouse_EventScript_GiveDurinBerry::",
  "Route123_BerryMastersHouse_EventScript_GiveBelueBerry::",
  "Route123_BerryMastersHouse_EventScript_GivePomegBerry::",
  "Route123_BerryMastersHouse_EventScript_GiveKeeBerry::",
  "Route123_BerryMastersHouse_EventScript_GiveMarangaBerry::",
  "Route123_BerryMastersHouse_EventScript_GiveSpelonBerry::",
  "Route123_BerryMastersHouse_EventScript_GivePamtreBerry::",
];
// const blacklist = ["VAR_0x8005", "VAR_RESULT"];
// const removeSimilarLocations = (duplicates: Duplicate[]) => {
//   for (const dupe of duplicates) {
//     if ()
//   }
// };
